---
apiVersion: v1
kind: Deployment
metadata:
  name: spindemo-{{ ENV }}
  namespace: default
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spindemo-{{ ENV }}
    spec:
      containers:
      - name: spinapp
        image: jasynetsky/spindemo
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: spindemo-{{ ENV }}
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: spindemo-{{ ENV }}
